import { Exercise, MuscleGroup, MuscleId } from '../models/types';

export const EXERCISES: Exercise[] = [
  // === Грудь ===
  {
    id: 'bench-press',
    name: 'Жим лёжа',
    muscleGroup: 'chest',
    equipment: 'Штанга',
    description: 'Базовое упражнение для грудных мышц. Лёжа на скамье, опустите штангу к груди и выжмите вверх.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif',
    targetMuscles: { primary: ['chest'], secondary: ['frontDelts', 'triceps'] },
  },
  {
    id: 'dumbbell-press',
    name: 'Жим гантелей лёжа',
    muscleGroup: 'chest',
    equipment: 'Гантели',
    description: 'Жим гантелей на горизонтальной скамье. Позволяет увеличить амплитуду движения.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Press.gif',
    targetMuscles: { primary: ['chest'], secondary: ['frontDelts', 'triceps'] },
  },
  {
    id: 'dumbbell-fly',
    name: 'Разводка гантелей',
    muscleGroup: 'chest',
    equipment: 'Гантели',
    description: 'Изолирующее упражнение. Разведите руки в стороны, слегка сгибая локти.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif',
    targetMuscles: { primary: ['chest'], secondary: ['frontDelts'] },
  },
  {
    id: 'push-ups',
    name: 'Отжимания',
    muscleGroup: 'chest',
    equipment: 'Собственный вес',
    description: 'Классическое упражнение. Опуститесь до касания грудью пола и отожмитесь.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Push-Up.gif',
    targetMuscles: { primary: ['chest'], secondary: ['frontDelts', 'triceps', 'abs'] },
  },
  {
    id: 'incline-barbell-press',
    name: 'Жим штанги на наклонной скамье',
    muscleGroup: 'chest',
    equipment: 'Штанга',
    description: 'Жим штанги на скамье под углом 30-45°. Акцент на верхнюю часть грудных мышц.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Barbell-Bench-Press.gif',
    targetMuscles: { primary: ['chest', 'frontDelts'], secondary: ['triceps'] },
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Жим гантелей на наклонной скамье',
    muscleGroup: 'chest',
    equipment: 'Гантели',
    description: 'Жим гантелей на наклонной скамье. Развивает верх грудных с большей амплитудой.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif',
    targetMuscles: { primary: ['chest', 'frontDelts'], secondary: ['triceps'] },
  },
  {
    id: 'cable-crossover',
    name: 'Сведение рук в кроссовере',
    muscleGroup: 'chest',
    equipment: 'Тренажёр',
    description: 'Сведение рук в блочном тренажёре. Изолирует грудные мышцы.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Cable-Crossover.gif',
    targetMuscles: { primary: ['chest'], secondary: ['frontDelts'] },
  },
  {
    id: 'decline-bench-press',
    name: 'Жим лёжа на наклонной скамье вниз',
    muscleGroup: 'chest',
    equipment: 'Штанга',
    description: 'Жим штанги на скамье с отрицательным наклоном. Акцент на нижнюю часть груди.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Smith-Machine-Decline-Bench-Press.gif',
    targetMuscles: { primary: ['chest'], secondary: ['triceps', 'frontDelts'] },
  },

  // === Спина ===
  {
    id: 'pull-ups',
    name: 'Подтягивания',
    muscleGroup: 'back',
    equipment: 'Турник',
    description: 'Базовое упражнение для широчайших мышц. Подтянитесь до подбородка выше перекладины.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif',
    targetMuscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'forearms'] },
  },
  {
    id: 'barbell-row',
    name: 'Тяга штанги в наклоне',
    muscleGroup: 'back',
    equipment: 'Штанга',
    description: 'Наклонитесь вперёд и тяните штангу к поясу. Держите спину прямой.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif',
    targetMuscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'lowerBack', 'rearDelts'] },
  },
  {
    id: 'lat-pulldown',
    name: 'Тяга верхнего блока',
    muscleGroup: 'back',
    equipment: 'Тренажёр',
    description: 'Тяните рукоять блока к груди, сводя лопатки.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif',
    targetMuscles: { primary: ['lats'], secondary: ['biceps', 'upperBack'] },
  },
  {
    id: 'dumbbell-row',
    name: 'Тяга гантели в наклоне',
    muscleGroup: 'back',
    equipment: 'Гантель',
    description: 'Одной рукой тяните гантель к поясу, опираясь другой рукой на скамью.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif',
    targetMuscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'rearDelts'] },
  },
  {
    id: 'seated-cable-row',
    name: 'Тяга нижнего блока',
    muscleGroup: 'back',
    equipment: 'Тренажёр',
    description: 'Тяга нижнего блока к поясу сидя. Развивает толщину спины.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif',
    targetMuscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'rearDelts'] },
  },
  {
    id: 't-bar-row',
    name: 'Тяга Т-грифа',
    muscleGroup: 'back',
    equipment: 'Штанга',
    description: 'Тяга Т-грифа в наклоне. Базовое упражнение для толщины спины.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lever-T-bar-Row.gif',
    targetMuscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'lowerBack'] },
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Пуловер на блоке',
    muscleGroup: 'back',
    equipment: 'Тренажёр',
    description: 'Пуловер стоя на верхнем блоке с прямыми руками. Изолирует широчайшие.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Cable-Straight-Arm-Pulldown.gif',
    targetMuscles: { primary: ['lats'], secondary: ['triceps', 'abs'] },
  },
  {
    id: 'chin-up',
    name: 'Подтягивания обратным хватом',
    muscleGroup: 'back',
    equipment: 'Турник',
    description: 'Подтягивания супинированным хватом. Дополнительно нагружает бицепс.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/Close-Grip-Chin-Up.gif',
    targetMuscles: { primary: ['lats', 'biceps'], secondary: ['upperBack', 'forearms'] },
  },

  // === Плечи ===
  {
    id: 'overhead-press',
    name: 'Жим стоя',
    muscleGroup: 'shoulders',
    equipment: 'Штанга',
    description: 'Выжмите штангу над головой из положения на уровне плеч.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/07/Barbell-Standing-Military-Press.gif',
    targetMuscles: { primary: ['frontDelts', 'sideDelts'], secondary: ['triceps', 'upperBack'] },
  },
  {
    id: 'lateral-raise',
    name: 'Махи в стороны',
    muscleGroup: 'shoulders',
    equipment: 'Гантели',
    description: 'Поднимите гантели в стороны до уровня плеч. Изолирует средний пучок дельт.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif',
    targetMuscles: { primary: ['sideDelts'], secondary: ['frontDelts'] },
  },
  {
    id: 'upright-row',
    name: 'Тяга к подбородку',
    muscleGroup: 'shoulders',
    equipment: 'Штанга',
    description: 'Тяните штангу вдоль тела вверх, разводя локти в стороны.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Upright-Row.gif',
    targetMuscles: { primary: ['sideDelts', 'frontDelts'], secondary: ['upperBack', 'biceps'] },
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Жим гантелей сидя',
    muscleGroup: 'shoulders',
    equipment: 'Гантели',
    description: 'Жим гантелей над головой сидя. Позволяет более естественную траекторию движения.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif',
    targetMuscles: { primary: ['frontDelts', 'sideDelts'], secondary: ['triceps'] },
  },
  {
    id: 'face-pull',
    name: 'Тяга к лицу',
    muscleGroup: 'shoulders',
    equipment: 'Тренажёр',
    description: 'Тяга верхнего блока к лицу с канатной рукоятью. Развивает задние дельты и ротаторы.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif',
    targetMuscles: { primary: ['rearDelts', 'upperBack'], secondary: ['biceps'] },
  },
  {
    id: 'front-raise',
    name: 'Подъём гантелей перед собой',
    muscleGroup: 'shoulders',
    equipment: 'Гантели',
    description: 'Подъём гантелей перед собой до уровня плеч. Изолирует передний пучок дельт.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Front-Raise.gif',
    targetMuscles: { primary: ['frontDelts'], secondary: ['sideDelts'] },
  },
  {
    id: 'rear-delt-fly',
    name: 'Разведение гантелей в наклоне',
    muscleGroup: 'shoulders',
    equipment: 'Гантели',
    description: 'Наклонитесь вперёд и разведите гантели в стороны. Развивает задний пучок дельт.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bent-Over-Lateral-Raise.gif',
    targetMuscles: { primary: ['rearDelts'], secondary: ['upperBack'] },
  },

  // === Бицепс ===
  {
    id: 'barbell-curl',
    name: 'Подъём штанги на бицепс',
    muscleGroup: 'biceps',
    equipment: 'Штанга',
    description: 'Стоя, согните руки со штангой. Локти прижаты к корпусу.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif',
    targetMuscles: { primary: ['biceps'], secondary: ['forearms'] },
  },
  {
    id: 'hammer-curl',
    name: 'Молотковые сгибания',
    muscleGroup: 'biceps',
    equipment: 'Гантели',
    description: 'Сгибания рук с нейтральным хватом. Развивает плечелучевую мышцу.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif',
    targetMuscles: { primary: ['biceps', 'forearms'], secondary: [] },
  },
  {
    id: 'concentration-curl',
    name: 'Концентрированные сгибания',
    muscleGroup: 'biceps',
    equipment: 'Гантель',
    description: 'Сидя, уприте локоть во внутреннюю часть бедра и согните руку.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif',
    targetMuscles: { primary: ['biceps'], secondary: [] },
  },
  {
    id: 'preacher-curl',
    name: 'Сгибания на скамье Скотта',
    muscleGroup: 'biceps',
    equipment: 'Штанга',
    description: 'Сгибания рук на скамье Скотта. Фиксирует локти для полной изоляции бицепса.',
    isCompound: false,
    targetMuscles: { primary: ['biceps'], secondary: ['forearms'] },
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Сгибания на наклонной скамье',
    muscleGroup: 'biceps',
    equipment: 'Гантели',
    description: 'Сгибания рук на наклонной скамье. Растягивает длинную головку бицепса.',
    isCompound: false,
    targetMuscles: { primary: ['biceps'], secondary: [] },
  },
  {
    id: 'cable-curl',
    name: 'Сгибания на нижнем блоке',
    muscleGroup: 'biceps',
    equipment: 'Тренажёр',
    description: 'Сгибания рук на нижнем блоке. Постоянное напряжение по всей амплитуде.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/cable-curl.gif',
    targetMuscles: { primary: ['biceps'], secondary: ['forearms'] },
  },
  {
    id: 'ez-bar-curl',
    name: 'Сгибания с EZ-грифом',
    muscleGroup: 'biceps',
    equipment: 'EZ-гриф',
    description: 'Сгибания рук с изогнутым грифом. Снижает нагрузку на запястья.',
    isCompound: false,
    targetMuscles: { primary: ['biceps'], secondary: ['forearms'] },
  },

  // === Трицепс ===
  {
    id: 'skull-crusher',
    name: 'Французский жим',
    muscleGroup: 'triceps',
    equipment: 'Штанга',
    description: 'Лёжа на скамье, опустите штангу ко лбу, сгибая только локти.',
    isCompound: false,
    targetMuscles: { primary: ['triceps'], secondary: [] },
  },
  {
    id: 'tricep-pushdown',
    name: 'Разгибания на блоке',
    muscleGroup: 'triceps',
    equipment: 'Тренажёр',
    description: 'Разгибайте руки на верхнем блоке, прижимая локти к корпусу.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif',
    targetMuscles: { primary: ['triceps'], secondary: [] },
  },
  {
    id: 'dips',
    name: 'Отжимания на брусьях',
    muscleGroup: 'triceps',
    equipment: 'Брусья',
    description: 'Опуститесь между брусьями и отожмитесь. Наклон вперёд — акцент на грудь, вертикально — на трицепс.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Chest-Dips.gif',
    targetMuscles: { primary: ['triceps', 'chest'], secondary: ['frontDelts'] },
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Французский жим гантелей стоя',
    muscleGroup: 'triceps',
    equipment: 'Гантель',
    description: 'Разгибания рук с гантелей за головой. Растягивает длинную головку трицепса.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Triceps-Extension.gif',
    targetMuscles: { primary: ['triceps'], secondary: [] },
  },
  {
    id: 'close-grip-bench-press',
    name: 'Жим узким хватом',
    muscleGroup: 'triceps',
    equipment: 'Штанга',
    description: 'Жим штанги лёжа узким хватом. Базовое упражнение для трицепса.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Close-Grip-Bench-Press.gif',
    targetMuscles: { primary: ['triceps', 'chest'], secondary: ['frontDelts'] },
  },
  {
    id: 'tricep-kickback',
    name: 'Отведение гантели назад',
    muscleGroup: 'triceps',
    equipment: 'Гантель',
    description: 'Отведение гантели назад в наклоне. Изолирует трицепс.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Kickback.gif',
    targetMuscles: { primary: ['triceps'], secondary: [] },
  },
  {
    id: 'diamond-push-up',
    name: 'Алмазные отжимания',
    muscleGroup: 'triceps',
    equipment: 'Собственный вес',
    description: 'Отжимания с узкой постановкой рук (алмаз). Акцент на трицепс.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Diamond-Push-up.gif',
    targetMuscles: { primary: ['triceps'], secondary: ['chest', 'frontDelts'] },
  },

  // === Ноги ===
  {
    id: 'squat',
    name: 'Приседания со штангой',
    muscleGroup: 'legs',
    equipment: 'Штанга',
    description: 'Базовое упражнение. Присядьте до параллели бёдер с полом.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif',
    targetMuscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'lowerBack', 'abs'] },
  },
  {
    id: 'leg-press',
    name: 'Жим ногами',
    muscleGroup: 'legs',
    equipment: 'Тренажёр',
    description: 'Выжимайте платформу ногами. Безопасная альтернатива приседаниям.',
    isCompound: true,
    targetMuscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'lunges',
    name: 'Выпады',
    muscleGroup: 'legs',
    equipment: 'Гантели',
    description: 'Шагните вперёд и опуститесь до прямого угла в коленях.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2023/09/dumbbell-lunges.gif',
    targetMuscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
  },
  {
    id: 'leg-extension',
    name: 'Разгибания ног',
    muscleGroup: 'legs',
    equipment: 'Тренажёр',
    description: 'Изолированная работа квадрицепса. Разгибайте ноги в тренажёре.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif',
    targetMuscles: { primary: ['quads'], secondary: [] },
  },
  {
    id: 'leg-curl',
    name: 'Сгибания ног',
    muscleGroup: 'legs',
    equipment: 'Тренажёр',
    description: 'Сгибания ног лёжа в тренажёре. Изолирует заднюю поверхность бедра.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif',
    targetMuscles: { primary: ['hamstrings'], secondary: ['calves'] },
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Болгарские выпады',
    muscleGroup: 'legs',
    equipment: 'Гантели',
    description: 'Выпады с задней ногой на возвышении. Развивает квадрицепсы и баланс.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif',
    targetMuscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'standing-calf-raise',
    name: 'Подъём на носки стоя',
    muscleGroup: 'legs',
    equipment: 'Тренажёр',
    description: 'Подъём на носки стоя в тренажёре. Развивает икроножные мышцы.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif',
    targetMuscles: { primary: ['calves'], secondary: [] },
  },
  {
    id: 'goblet-squat',
    name: 'Гоблет приседания',
    muscleGroup: 'legs',
    equipment: 'Гантель',
    description: 'Приседания с гантелей у груди. Отлично подходит для обучения технике.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2023/01/Dumbbell-Goblet-Squat.gif',
    targetMuscles: { primary: ['quads', 'glutes'], secondary: ['abs', 'hamstrings'] },
  },

  // === Ягодицы ===
  {
    id: 'hip-thrust',
    name: 'Ягодичный мост',
    muscleGroup: 'glutes',
    equipment: 'Штанга',
    description: 'Упритесь спиной в скамью и поднимите таз со штангой на бёдрах.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif',
    targetMuscles: { primary: ['glutes'], secondary: ['hamstrings', 'lowerBack'] },
  },
  {
    id: 'romanian-deadlift',
    name: 'Румынская тяга',
    muscleGroup: 'glutes',
    equipment: 'Штанга',
    description: 'Наклонитесь вперёд с почти прямыми ногами, растягивая заднюю поверхность бедра.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Romanian-Deadlift.gif',
    targetMuscles: { primary: ['hamstrings', 'glutes'], secondary: ['lowerBack', 'forearms'] },
  },
  {
    id: 'cable-kickback',
    name: 'Отведение ноги в кроссовере',
    muscleGroup: 'glutes',
    equipment: 'Тренажёр',
    description: 'Отведение ноги назад в блочном тренажёре. Изолирует ягодичные мышцы.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Cable-Donkey-Kickback.gif',
    targetMuscles: { primary: ['glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'glute-bridge',
    name: 'Ягодичный мост без веса',
    muscleGroup: 'glutes',
    equipment: 'Собственный вес',
    description: 'Мост лёжа на полу. Базовое упражнение для активации ягодиц.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/12/Barbell-Glute-Bridge.gif',
    targetMuscles: { primary: ['glutes'], secondary: ['hamstrings', 'abs'] },
  },
  {
    id: 'sumo-deadlift',
    name: 'Тяга сумо',
    muscleGroup: 'glutes',
    equipment: 'Штанга',
    description: 'Становая тяга с широкой постановкой ног. Акцент на ягодицы и внутреннюю поверхность бедра.',
    isCompound: true,
    targetMuscles: { primary: ['glutes', 'quads'], secondary: ['hamstrings', 'lowerBack', 'forearms'] },
  },
  {
    id: 'dumbbell-step-up',
    name: 'Зашагивания на платформу',
    muscleGroup: 'glutes',
    equipment: 'Гантели',
    description: 'Зашагивания на платформу с гантелями. Развивает ягодицы и квадрицепсы.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Step-up.gif',
    targetMuscles: { primary: ['glutes', 'quads'], secondary: ['hamstrings', 'calves'] },
  },

  // === Пресс ===
  {
    id: 'crunches',
    name: 'Скручивания',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Лёжа на спине, поднимите плечи от пола, сокращая мышцы пресса.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Floor-Crunch.gif',
    targetMuscles: { primary: ['abs'], secondary: [] },
  },
  {
    id: 'plank',
    name: 'Планка',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Статическое упражнение. Удерживайте тело в прямой линии на предплечьях.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/plank.gif',
    targetMuscles: { primary: ['abs'], secondary: ['obliques', 'lowerBack', 'shoulders'] },
  },
  {
    id: 'leg-raise',
    name: 'Подъём ног',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Лёжа на спине или в висе, поднимите прямые ноги вверх.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lying-Leg-Raise.gif',
    targetMuscles: { primary: ['abs', 'hip-flexors'], secondary: ['obliques'] },
  },
  {
    id: 'russian-twist',
    name: 'Русские скручивания',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Скручивания корпуса сидя с поворотом. Развивает косые мышцы пресса.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Russian-Twist.gif',
    targetMuscles: { primary: ['obliques', 'abs'], secondary: [] },
  },
  {
    id: 'bicycle-crunch',
    name: 'Велосипед',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Скручивания с поочерёдным касанием локтём колена. Комплексная работа пресса.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bicycle-Crunch.gif',
    targetMuscles: { primary: ['abs', 'obliques'], secondary: ['hip-flexors'] },
  },
  {
    id: 'mountain-climber',
    name: 'Скалолаз',
    muscleGroup: 'abs',
    equipment: 'Собственный вес',
    description: 'Попеременное подтягивание коленей к груди в упоре лёжа. Кардио + пресс.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Mountain-climber.gif',
    targetMuscles: { primary: ['abs', 'hip-flexors'], secondary: ['shoulders', 'quads', 'cardio'] },
  },
  {
    id: 'hanging-leg-raise',
    name: 'Подъём ног в висе',
    muscleGroup: 'abs',
    equipment: 'Турник',
    description: 'Подъём прямых ног в висе на перекладине. Развивает нижний пресс.',
    isCompound: false,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/08/Hanging-Leg-Raises.gif',
    targetMuscles: { primary: ['abs', 'hip-flexors'], secondary: ['forearms', 'obliques'] },
  },

  // === Кардио ===
  {
    id: 'running',
    name: 'Бег',
    muscleGroup: 'cardio',
    equipment: 'Беговая дорожка',
    description: 'Кардио-тренировка. Укажите дистанцию или время в заметках.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Treadmill-.gif',
    targetMuscles: { primary: ['cardio'], secondary: ['quads', 'hamstrings', 'calves', 'glutes'] },
  },
  {
    id: 'cycling',
    name: 'Велотренажёр',
    muscleGroup: 'cardio',
    equipment: 'Велотренажёр',
    description: 'Кардио на велотренажёре. Укажите время и сопротивление в заметках.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2022/06/Recumbent-Exercise-Bike.gif',
    targetMuscles: { primary: ['cardio', 'quads'], secondary: ['hamstrings', 'calves', 'glutes'] },
  },
  {
    id: 'jump-rope',
    name: 'Скакалка',
    muscleGroup: 'cardio',
    equipment: 'Скакалка',
    description: 'Прыжки через скакалку. Отличное кардио для координации и выносливости.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2023/10/Skip-Jump-Rope.gif',
    targetMuscles: { primary: ['cardio', 'calves'], secondary: ['shoulders', 'forearms'] },
  },
  {
    id: 'rowing-machine',
    name: 'Гребной тренажёр',
    muscleGroup: 'cardio',
    equipment: 'Тренажёр',
    description: 'Гребля на тренажёре. Комплексная кардио-нагрузка на всё тело.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Rowing-Machine.gif',
    targetMuscles: { primary: ['cardio', 'lats', 'upperBack'], secondary: ['biceps', 'quads', 'hamstrings'] },
  },
  {
    id: 'elliptical',
    name: 'Эллиптический тренажёр',
    muscleGroup: 'cardio',
    equipment: 'Тренажёр',
    description: 'Тренировка на эллиптическом тренажёре. Щадящая нагрузка на суставы.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/10/Elliptical-Machine.gif',
    targetMuscles: { primary: ['cardio'], secondary: ['quads', 'hamstrings', 'glutes'] },
  },
  {
    id: 'jumping-jacks',
    name: 'Прыжки с разведением рук',
    muscleGroup: 'cardio',
    equipment: 'Собственный вес',
    description: 'Прыжки с одновременным разведением рук и ног. Простое и эффективное кардио.',
    isCompound: true,
    targetMuscles: { primary: ['cardio'], secondary: ['shoulders', 'calves'] },
  },

  // === Всё тело ===
  {
    id: 'burpees',
    name: 'Бёрпи',
    muscleGroup: 'fullBody',
    equipment: 'Собственный вес',
    description: 'Присядьте, прыгните в упор лёжа, отожмитесь, вернитесь и подпрыгните.',
    isCompound: true,
    targetMuscles: { primary: ['cardio', 'chest', 'quads'], secondary: ['shoulders', 'triceps', 'abs', 'glutes'] },
  },
  {
    id: 'deadlift',
    name: 'Становая тяга',
    muscleGroup: 'fullBody',
    equipment: 'Штанга',
    description: 'Базовое упражнение. Поднимите штангу с пола, разгибая ноги и спину.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif',
    targetMuscles: { primary: ['lowerBack', 'hamstrings', 'glutes'], secondary: ['quads', 'lats', 'forearms', 'upperBack'] },
  },
  {
    id: 'clean-and-press',
    name: 'Взятие и жим штанги',
    muscleGroup: 'fullBody',
    equipment: 'Штанга',
    description: 'Взятие штанги на грудь и жим над головой. Мощное силовое движение для всего тела.',
    isCompound: true,
    targetMuscles: { primary: ['shoulders', 'quads', 'glutes'], secondary: ['hamstrings', 'triceps', 'upperBack', 'lowerBack'] },
  },
  {
    id: 'kettlebell-swing',
    name: 'Махи гирей',
    muscleGroup: 'fullBody',
    equipment: 'Гиря',
    description: 'Махи гирей между ног с выносом вперёд. Развивает взрывную силу задней цепи.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2021/09/Kettlebell-Swings.gif',
    targetMuscles: { primary: ['glutes', 'hamstrings'], secondary: ['lowerBack', 'shoulders', 'abs', 'forearms'] },
  },
  {
    id: 'thrusters',
    name: 'Трастеры',
    muscleGroup: 'fullBody',
    equipment: 'Штанга',
    description: 'Приседание со штангой с последующим жимом над головой. Комплексное упражнение.',
    isCompound: true,
    gifUrl: 'https://fitnessprogramer.com/wp-content/uploads/2022/10/thruster.gif',
    targetMuscles: { primary: ['quads', 'glutes', 'shoulders'], secondary: ['triceps', 'abs', 'hamstrings'] },
  },
  {
    id: 'man-maker',
    name: 'Мэнмейкер',
    muscleGroup: 'fullBody',
    equipment: 'Гантели',
    description: 'Отжимание + тяга в наклоне + выпрыгивание + жим с гантелями. Максимальная нагрузка.',
    isCompound: true,
    targetMuscles: { primary: ['chest', 'shoulders', 'quads'], secondary: ['triceps', 'lats', 'abs', 'glutes'] },
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByGroup(group: MuscleGroup): Exercise[] {
  return EXERCISES.filter((e) => e.muscleGroup === group);
}

export function getAllMuscleGroups(): MuscleGroup[] {
  return ['chest', 'back', 'shoulders', 'biceps', 'triceps', 'legs', 'glutes', 'abs', 'cardio', 'fullBody'];
}
